# Generated by Django 2.1.5 on 2019-01-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsheet',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
